### ISSUE TITLE
typo in link on README

### ISSUE THREAD

**Issue by ghost** [40ants/lisp-project-of-the-day#1]
Greetings! I'm eagerly following your posts. Good show.

Just reporting a typo:

https://github.com/40ants/lisp-project-of-the-day/blob/master/content/2020/04/0029-skippy 

should be

https://github.com/40ants/lisp-project-of-the-day/blob/master/content/2020/04/0029-skippy.org

Cheers

**Comment by svetlyak40wt** [comment]
Thank you. Fixed in https://github.com/40ants/lisp-project-of-the-day/commit/5206869f5837e839eb9b8111e98ea4856a3ad528
